DROP TABLE IF EXISTS PUBLIC.BOOK;

CREATE TABLE PUBLIC.BOOK
(
    ID             INTEGER      NOT NULL AUTO_INCREMENT,
    BOOK_NAME      VARCHAR(255) NOT NULL,
    BOOK_PUBLISHER INTEGER      NOT NULL REFERENCES PUBLISHER (ID),
    BOOK_AUTHOR    VARCHAR(255) NOT NULL,
    BOOK_PUBLISH   INTEGER      NOT NULL,
    CONSTRAINT BOOK_PRIMARY_KEY PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PUBLIC.NEWSPAPER;

CREATE TABLE PUBLIC.NEWSPAPER
(
    ID                  INTEGER      NOT NULL AUTO_INCREMENT,
    NEWSPAPER_NAME      VARCHAR(255) NOT NULL,
    NEWSPAPER_PUBLISHER INTEGER      NOT NULL REFERENCES PUBLISHER (ID),
    CONSTRAINT NEWSPAPER_PRIMARY_KEY PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PUBLIC.MAGAZINE;

CREATE TABLE PUBLIC.MAGAZINE
(
    ID                 INTEGER      NOT NULL AUTO_INCREMENT,
    MAGAZINE_NAME      VARCHAR(255) NOT NULL,
    MAGAZINE_PUBLISHER INTEGER      NOT NULL REFERENCES PUBLISHER (ID),
    CONSTRAINT MAGAZINE_PRIMARY_KEY PRIMARY KEY (ID)
);



CREATE TABLE PUBLIC.PUBLISHER
(
    ID        INTEGER      NOT NULL AUTO_INCREMENT,
    PUBLISHER VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT PUBLISHER_PRIMARY_KEY PRIMARY KEY (ID)
);
